### ISSUE TITLE
Event groups don't have a persistent source type

### ISSUE THREAD

**Issue by PaulHancock** [ADACS-Australia/mwa_trigger#82]
The source type for all events within an event group should be the same, but this is not always being done. For example this group has some events labeled as GRB, and some as not GRBs: https://mwa-trigger.duckdns.org/event_group_details/4796/

**Comment by NickSwainston** [comment]
I don't think this is an issue/incorrect. The logic only requires the one (the first instance) of a source type to be declared, then it doesn't check the source type after the first trigger. 

So it doesn't trigger on the FOM_Obs and BAT_QuickLook_Pos because it can't tell that it's a GRB. The BAT_GRB_Pos knows it's a GRB, so this is the first trigger. The rest of the FOM_Obs are considered, but we don't do anything because they have a 0.0 position error.

I think retroactively changing the source types on individual events will make it harder to trace back what the logic did.

**Comment by NickSwainston** [comment]
Using the source name as we discussed actually solves this
